Algoritmo "crescente"




Var

   x, y: inteiro


Inicio

      escreva ("Digite o x: ")
      leia (x)
      escreva ("Digite o y: ")
      leia (y)

      enquanto x <> y faca

      se x < y entao
         escreval ("Crescente")
      senao
        escreval ("Decrescente")
      fimse
      
      escreva ("Digite o x: ")
      leia (x)
      escreva ("Digite o y: ")
      leia (y)
      
      fimenquanto


Fimalgoritmo